apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: argocd
spec:
  destination:
    namespace: asset
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: services
    directory:
      recurse: true
    repoURL: 'https://github.com/fanxwsam/asset-apps-argocd.git'
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
