apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  destination:
    namespace: asset
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: bootstrap
    repoURL: 'https://github.com/fanxwsam/asset-apps.git'
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
